# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(default='/media', upload_to='/media'),
        ),
    ]
