# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20160501_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
