# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=20)),
                ('linkedin', models.CharField(max_length=20)),
                ('outras_redes', models.CharField(max_length=100)),
                ('lutas', models.CharField(max_length=100)),
                ('stacks', models.CharField(max_length=100)),
                ('eventos', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
    ]
