# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20160327_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(default='/media', null=True, upload_to='/media'),
        ),
    ]
